### ISSUE TITLE
Define colaboration model

### ISSUE THREAD

**Issue by McSinyx** [Huy-Ngo/acanban#10]
*No, this has nothing to do with the UML.*

In the next few months, we'll have a team of five working on this project.  To avoid synchronization problems, let's lay out a few guidelines so that we won't shoot/step on each others' feet.  I'll start with my preference:

1. Every routine (function/method) needs tests.  As human being, we might not enforce this to 100%, but if one implements something, perse MUST either write tests for it or make a *super valid* excuse for not doing so.
2. Every non-trivial change needs at least 2 approving reviews.  By trivial, I mean stuff like editing typos, bumping versions and rephrasing sentences.  Things that are very unlikely to create regression of any kind.  When in doubt, your patches are non-trivial and you should file a PR.
3. Don't use merge commits.  @Huy-Ngo, as the admin of this repo, could you please switch off such feature (so that only rebase and squash and rebase are possible)?  Also I think it's possible to enforce (2) as well.
4. Try to do something everyday (OK, maybe 5 days a week so that we won't get burnouts).  Not necessary writing code, but dropping a comment here and there, file a new issue, reorganize the kanbans, etc.  Make sure that thing progresses.
5. Pay attention to details.  @Huy-Ngo and @9a24f0 probably still remember how bad my OCD is, but to @DDHLong and @Yus147, I'm bat-shit crazy when it comes to code formatting.  We'll use some sort of linter to enforce this after agreeing on styling but always double check your patches before submitting.  Failing linters is the best way to drive people away from reviewing one's code.

Feel free to discuss on the points listed above and add what you think would make the colab more efficient.  Cheers!

**Comment by McSinyx** [comment]
Looking at GH-25, I start to think we'll need to have a release/milestone kind of thing.  Also would it be a good idea to publish this on PyPI?

**Comment by Huy-Ngo** [comment]
> Also would it be a good idea to publish this on PyPI?

I'm not sure about that. On one hand it would be quite convenient to have one-line installation if the USTH wants to install on a different machine later; on the other hand that package seems oddly specific and usable for only one uni, apparently?

**Comment by McSinyx** [comment]
> package seems oddly specific and usable for only one uni

How so?  AFAIK the only things that are specific to USTH are (1) the mail server and (2) the record templates, both of which should be separated from the package.
