### ISSUE TITLE
Label the use case diagrams and refer to them in the documents

### ISSUE THREAD

**Issue by Huy-Ngo** [Huy-Ngo/acanban#129]
The figures (mostly UML diagrams) are not labeled and referenced in the text. I am not aware of a way to label it, though.

**Comment by Huy-Ngo** [comment]
Hmm since we found the way, let's close this. I should change the name.

**Comment by Huy-Ngo** [comment]
It is configured in 168b461 and labelled in a95946e

**Comment by McSinyx** [comment]
Seems to be resolved at the time of writing.
