### ISSUE TITLE
Revise documentation structure

### ISSUE THREAD

**Issue by McSinyx** [Huy-Ngo/acanban#15]
In GH-9, I defined the doc structure based on OOSAD documents.  While technically there's nothing wrong with that, it utterly useless in our case, since we won't need the OOSAD doc for anything.  Rather, let's use `docs/` for the group project report and `README` for the description, setup, usage thing.

Alors, the main question here is what must and what can the report include and what its structure is exactly.  Maybe some input from Dr @nqdoan13 would help.  The sooner we define it, the less time need we spent refactoring the documents (yes I see how strange this sounds).

Edit: [this guide](https://www.cs.cmu.edu/~Compose/shaw-icse03.pdf) seems to be a nice one to help us indicate what to be done/what is expected.

**Comment by 9a24f0** [comment]
This idea comes through my observation at thesis defense of BI8 students that we will have a section call methodology where it includes how we design the system, i.e: UC model with descriptions, DB design, etc. We will refactor it in a full report later on, for now I suggest just finish what we're doing.

**Comment by McSinyx** [comment]
By later on, I assume that it's right after the next sync, i.e. this Tuesday.

**Comment by Huy-Ngo** [comment]
> Edit: output of the offline discussion is posted in #16 (comment).

Whoops... I thought I posted it here. I posted there by mistake.
