### ISSUE TITLE
Why are we doing this?

### ISSUE THREAD

**Issue by McSinyx** [Huy-Ngo/acanban#16]
No, not in the sense of *cuz 3 credits are 3 credits*, but rather why we'd get 3 credits from doing this. Or, even, what are we doing exactly?  There are plenty of libre and well-tested project management systems in the wild, and I suppose there's at least one or two that support the grading use case.  Or is there?  We need to find out for the problem statement.

**Comment by Huy-Ngo** [comment]
There isn't actually much to do in this project, or so I was told. Do you mean, what novel features we can add to this system? We can't know that without taking looks at other projects (well we were supposed to do this 2 weeks ago). Do you have some examples of previously done projects so we all can discuss on which features can be added?

**Comment by McSinyx** [comment]
No, hence the questions (they were phrased in a way that answers can be used for report's introduction/problem statement, not exactly honest questions to be fair).  `paraphrase('school', 'project management software')` isn't the best query ever, and [the meta article on Wikipedia](https://en.wikipedia.org/wiki/Comparison_of_project_management_software) doesn't give insight about the grading thing.  I suppose that software like what we are building is obsolete *enough*, but don't really have proof for it.

**Comment by Huy-Ngo** [comment]
Here are the sections that should be there in the report:

- Introduction
- Objective
- Expected outcome
- Requirements
- Architecture
- System solution
- ...

**Comment by Huy-Ngo** [comment]
Per offline discussion last Friday, we have (at least) 3 objectives:

- To facilitate collaboration between members as well as supervision
- To store the database of past school project
- To digitize evaluation and academic reports, which make things easier for academic assistants and supervisors. Supposedly students would gain from receiving their results earlier.

I believe most other project management software just fulfill the first two requirements, but not the third one.
