### ISSUE TITLE
'members' multi-index misbehaves when the project only have students or supervisors

### ISSUE THREAD

**Issue by McSinyx** [Huy-Ngo/acanban#180]
This is a regression introduced by GH-167.

**Comment by Huy-Ngo** [comment]
Ohh, that's why

**Comment by Huy-Ngo** [comment]
Looking at the current database, it seems that thou implemented the index with

```py
r.table('projects').index_create('members', r.row['students'] + r.row['supervisors'])
```

Is that correct?

According to [RethinkDB doc](https://rethinkdb.com/docs/secondary-indexes/python/#creation-1), it seems that it should be:

```py
r.table('projects').index_create('members', [r.row['students'], r.row['supervisors']])
```

**Comment by McSinyx** [comment]
> thou implemented the index with [...]  Is that correct?

Yep.

> it seems that it should be: [...]

That's for compound index, which is different from multi index.  I can think of two fixes:

1. Change the index expression to something equivalent to `r.row.get('students', []) + r.row.get('supervisors', [])` in Python
2. Ensure every project object has both fields
