### ISSUE TITLE
Define clearer outcome in the objective

### ISSUE THREAD

**Issue by Huy-Ngo** [Huy-Ngo/acanban#187]
Current expected outcome is too vague.

**Comment by Huy-Ngo** [comment]
Also add [Business Functional Decomposition](https://thefunctionalba.com/2019/12/functional-decomposition-in-business-analysis/)

**Comment by Huy-Ngo** [comment]
I suppose [WBS diagram](https://plantuml.com/wbs-diagram) can be helpful

**Comment by Huy-Ngo** [comment]
God I love PlantUML

**Comment by McSinyx** [comment]
This should be part of requirement engineering IMHO.

**Comment by McSinyx** [comment]
I'm stealing this, use GH-203 for WBS.

**Comment by Huy-Ngo** [comment]
OK then
