### ISSUE TITLE
New way to document JSON database

### ISSUE THREAD

**Issue by Huy-Ngo** [Huy-Ngo/acanban#22]
The wrong JSON syntax prevents Sphinx from parsing it and doesn't highlight the keys, which annoys me.

**Comment by McSinyx** [comment]
Python typing (PEP 484) might suits the current data structure definition.

**Comment by Huy-Ngo** [comment]
Maybe something like this:

------

```json
{
  "id": "string",
  "title": "string",
  "tasks": "array",
  ...
}
```
- `id`: A UUID for the project
- `title`: The title of the project
- `tasks`: A list of tasks of the project
- ...

**Comment by McSinyx** [comment]
It's bikesheding, but I'd rather *read* something less obfuscated by quotes (JSON have quotes because it makes it easier for *machines* to parse, not human).

My suggestion for human consumption syntax would be something like

```
Comment:
   uuid (str): unique identifier of the comment
   content (str): content of the comment
   comments (list of Comment): child comments
```

If we don't want to invent new language, Python type annotation is quite handy, e.g.

```python
class Comment:
    uuid: str  # unique identifier of the comment
    content: str  # content of the comment
    comments: List[Comment]  # child comments
```

**Comment by Huy-Ngo** [comment]
I just looked up and there is a thing called [JSON Schema](https://json-schema.org/learn/getting-started-step-by-step.html) which seems quite verbose. It would look like:

```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/project.schema.json",
  "title": "Project",
  "description": "A project...",
  "type": "object",
  "properties": {
    "id": {
      "description": "The unique identifier for a project",
      "type": "string"
    },
    "title": {
      "description": "The title of the project",
      "type": "string"
    },
    "tasks": {
      "description": "A list of tasks of the project",
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 0,
      "uniqueItems": true
    }
  }
}
```

**Comment by Huy-Ngo** [comment]
I'm not fond of the idea using python class notation because that'd imply we're using Python classes here (we don't, do we?).

Maybe we can write like:

> Each **`Project`** object have following attributes:
> 
> - `id` (`string`): A UUID for the project
> - `title` (`string`): The title of the project
> - `tasks` (`array` of **`Task`**, optional): A list of tasks of the project
> - ...

**Comment by McSinyx** [comment]
Yea, that LGTM as well.
