### ISSUE TITLE
Render comments as markdown

### ISSUE THREAD

**Issue by McSinyx** [Huy-Ngo/acanban#229]

**Comment by Huy-Ngo** [comment]
Pretty sure there's a markdown parser for Python.

**Comment by McSinyx** [comment]
Oh thank Guido, there is!  Wanna take this up?  I'm thinking about
adding a lib as a jinja2 filter.

**Comment by Huy-Ngo** [comment]
That's fine by me. I saw [an extension for Jinja](https://pypi.org/project/jinja-markdown/) But I'm not sure about its security. There can be some kind of HTML/CSS/JS injection there isn't it?

**Comment by McSinyx** [comment]
Yes, we'll need to whitelist tags, where just p, a, emph, strong
(pretty sure these are LaTeX), ul/ol+li, h{1..6}, img, table
and code renderring (inline and block) would cover 99% of the cases
already.

**Comment by Huy-Ngo** [comment]
> emph, strong (pretty sure these are LaTeX),

HTML uses em and strong iirc

**Comment by McSinyx** [comment]
Reopening, just realized we missed the evaluation comments by supervisors.

**Comment by Huy-Ngo** [comment]
You implemented it as input field instead of a div field

**Comment by McSinyx** [comment]
Change it, it's called software for a reason.

**Comment by McSinyx** [comment]
Gentle ping!

**Comment by Huy-Ngo** [comment]
You better shouldn't have made things in non-traditional way at the first place
