### ISSUE TITLE
Use project base for task view

### ISSUE THREAD

**Issue by Huy-Ngo** [Huy-Ngo/acanban#237]
![image](https://user-images.githubusercontent.com/19296926/108724021-732f0d00-7557-11eb-822a-b27793c81b52.png)
This view is inconsistent with other views because it doesn't have a project navbar like other views. At first glance it looks like this is a project of its own.

**Comment by McSinyx** [comment]
I'll tackle this as part of task metadata edit (I'm planning
to use the same page for it).
