### ISSUE TITLE
[Use case] How to look for supervisor?

### ISSUE THREAD

**Issue by Huy-Ngo** [Huy-Ngo/acanban#31]
Do we have a way for the student to request the supervisor yet?

In practice, we have seen these cases:

- The students form a group and ask for supervision, the supervisor proposes some projects, the students accept one of the project
- The students form a group and ask for supervision, the supervisor accepts the invitation but does not provide a project, the students propose a project, the supervisor approves the project
- The supervisor proposes some projects, the students form a group and ask for supervision

(Maybe I was missing some cases)

Do they have to discuss offline beforehand?

**Comment by McSinyx** [comment]
Passing by to say the discussion label is quite overused, usually it's used for design discussions (i.e. this is what I want to implement, these are the choices, so which way should I choose and why?).  I'm not in the mental space to think about this at the moment though.

**Comment by Huy-Ngo** [comment]
Yes, they have to discuss beforehand.
