### ISSUE TITLE
Handle uploaded files

### ISSUE THREAD

**Issue by Huy-Ngo** [Huy-Ngo/acanban#33]
In the UC "Complete Task", students have to upload file(s) as evidence for their work. However, I didn't design the database for this yet (should I do it in #32 ?)

I have never handle file hosting before, so my idea isn't the best. Here is the rough mechanism for storing it I have in mind:

- The file is stored in a dedicated directory on the server
- The file can be distributed by IPFS for better throughput (?)(*)
- The database store the metadata of the file (e.g. file name, URL, uploader, ...)

Possible threats: the uploaded files could be malicious and break the system.

Is it good enough approach or could it improved? 

(*): I haven't used IPFS before either so I don't know how it work.

**Comment by 9a24f0** [comment]
I suggest we discuss this on tmr session with Dr.Quang, we could do sth similiar to moodle, but the implementation is with IPFS (?)

**Comment by McSinyx** [comment]
This is what I *think* [howz it mizzade](https://www.youtube.com/watch?v=1Fl2sMV7Hcc):

1. User send us a file through a HTTP request
2. We retrieve the request and get the binary content
3. We give the binary content to IPFS and get back the hash
4. We add the hash and other metadata to the DB
5. User ask for the file
6. We either give user the IPFS link (if our node is popular enough for the gateway to discover us quickly) or stream it from IPFS to the user

> the uploaded files could be malicious and break the system

We shouldn't ever try to open it.  Data can't break the system.  Only doing things with data could.

**Comment by Huy-Ngo** [comment]
I was thinking of [Directory traversal attack](https://en.wikipedia.org/wiki/Directory_traversal_attack) but apparently IPFS does not allow it anyway.
