### ISSUE TITLE
Design frontend interface

### ISSUE THREAD

**Issue by Huy-Ngo** [Huy-Ngo/acanban#34]
This issue includes:

- Listing what views should the frontend has, based on the UC model (can communicate with @9a24f0 to refine the UCM if needed)
- Document these decision
- Draw it (is it actually necessary?)
- Implement with code

**Comment by DDHLong** [comment]
The prototype will reduce rework. If I code the whole thing and you don't satisfy with something I have to change a lot. So instead of that, we all agree on the prototype then code.

**Comment by McSinyx** [comment]
This is too broad: we better split it into incrementally solvable tickets.  BTW regarding future reviewing process, I suggest providing screenshots in the PRs (because I'm too lazy to fetch the branch and starts the server locally, that's why) in the following cases:

* B I G screen, maybe width of 1920 should be OK, anything larger prolly have HiDPI enabled
* Small screen, mainly for tablets and splits, so maybe 720?
* Phone screen, maybe around 360?

**Comment by McSinyx** [comment]
Let's use this as the tracker for overall front-end decisions.  One thing I would love having attention to beside the look is the performance.  For example, notice how shitty sites like GitHub is taking 5 precious seconds of my life to load on a 2018 mid-end laptop through a 50 Mbps connection.

![2020-12-09T11:14:40](https://user-images.githubusercontent.com/13689192/101584343-056f4c80-3a10-11eb-95c8-419912c38407.png)

Despite the actual content is just some text, some geniuses decided that I will have to download 1.5 MB of garbage in nearly 30 requests.  And that I'll have to run some whatever code emulated by a fucking web browser to render the HTML, which is *then* rendered by the browser itself.  JS is not always bad, but the giant ones are awful (note the bottlenecks).

GitLab is even worse (this is why I'm not very fond of using it, despite it's FLOSS; Gitea and SourceHut on the other hand are super light and pleasing to interact with).  Please don't follow bad examples, no matter how seemingly successful they are.  See also: [the *best* motherfucking website](https://thebestmotherfucking.website) (yes, I understand it's satire, and no, we don't have to be as boring, but the author got a point on the technical metrics).

**Comment by McSinyx** [comment]
Closing since the scope of this is too broad.  Feel free to open new ones you notice them.
