### ISSUE TITLE
Split files into modules

### ISSUE THREAD

**Issue by Huy-Ngo** [Huy-Ngo/acanban#48]
If our project grows too big for files to handle them (we haven't reached that point yet), we should [split files into modules](https://lepture.com/en/2018/structure-of-a-flask-project) according to their functions. This can be tricky because it may lead to high coupling and loose cohesion if we don't design it carefully. Let's leave this issue open until we have time to think carefully about this.

**Comment by McSinyx** [comment]
Lol how is this low priority, technically it's about architecture, the most important thing to consider :smile:  Regarding the linked article, I think it'd be easier to use the *app-based structure* thing (we already are).  See also [Quart docs](http://pgjones.gitlab.io/quart/tutorials/large_application.html) for the shorter explanation.

**Comment by Huy-Ngo** [comment]
It's low priority because we're not solving it before this Friday lol. 

> I think it'd be easier to use the app-based structure thing (we already do).

I agree. What I mean is the current `auth.py` file includes everything inside it, which can be clumsy and a bit hard to navigate if we want to update some functionality.

**Comment by McSinyx** [comment]
In that case, just split it out (IIRC nested blueprint is supported).  When in doubts, smaller modules > larger ones.

**Comment by Huy-Ngo** [comment]
If the next modules require splitting then just split it, no need for this issue to open anymore.
