### ISSUE TITLE
Use config for app initialization

### ISSUE THREAD

**Issue by Huy-Ngo** [Huy-Ngo/acanban#50]
In `__init__.py`, we are using `test` db for all instances created:

https://github.com/Huy-Ngo/acanban/blob/39b948fde23cf06c83b6183699df04b0eb7d3a55/src/acanban/__init__.py#L70

The db should be different for testing (`test` db) and deployment (`acanban` db, not created yet). This can be achieved by config.

**Comment by McSinyx** [comment]
Currently RethinkDB address (host and port) is also hard-coded as well.
