### ISSUE TITLE
Add more components for landing page after logging in

### ISSUE THREAD

**Issue by Huy-Ngo** [Huy-Ngo/acanban#64]
Currently, after logging in, User is redirected to a page that is the same as before. Let's change this to displaying the user's dashboard and add more links at the navbar.

The navbar may contain:

- Projects
- Tasks (create mock db for this too)

The dashboard may be just the list of the projects of the user for now.

**Comment by McSinyx** [comment]
I'm thinking about using it for notification/feed like in other social midea (e.g. GitHub).  If we do it, we can skip email integration for now (I'm sorry Drew) and save some time focusing on more urgent features.  We still need to pin down how notifications are to be stored in the DB though.

**Comment by Huy-Ngo** [comment]
I suppose each user can have a field for that (queue-like list) in User.

**Comment by McSinyx** [comment]
Shower thoughts: *Notification* should have at least the *who*, the *do what* and the *when* (renamed appropriately), and *User* should have an additional field *tz* so that we can store notification time in UTC (pganssle should be proud of me!).

**Comment by Huy-Ngo** [comment]
Aight I'm actually not sure if we do notification faster via email or this.
