### ISSUE TITLE
Link projects from users

### ISSUE THREAD

**Issue by Huy-Ngo** [Huy-Ngo/acanban#71]
Currently, the relation between `User` and `Project` is done via the participant list in projects. This was initially done considering that the number of project is fewer than the number of students. However, this would make it harder to look for projects: whenever someone wants to see their own project, the system would have to list all projects and filter by their participant list. However, when we go to a project it would also list the participants of the project.

I'm not sure which one would benefits more. Maybe I'm just overthinking this and keeping it as is is fine.

**Comment by McSinyx** [comment]
Why not both?

```rst
User
----

Each ``User`` object has following attributes:

...

``projects`` : ``array`` of ``string``
   UUID of projects perse is participating in.

Project
-------

Each ``Project`` object has following attributes:

``uuid`` : ``string``
    Universally unique identifier.

``name`` : ``string``
   The name of the project.

``description`` : ``string``
   The summary of a project.

``participants`` : ``array`` of ``string``
   Usernames of those participating in the project.

``tasks`` : ``array`` of ``Task``
   List of ``Task``\s created for this project.
```

Since we can't index arrays (or can we?), this would get the operations described above down to Θ(log n).  Note that `creator` and `supervisor` fields in Project are suggested to be removed because there's no benefit of knowing the creator and supervisors are participants.

**Comment by Huy-Ngo** [comment]
RethinkDB doesn't recommend that way, but well, NoSQL doesn't care about redundancy so I guess that option is ok too.

> Note that `creator` and `supervisor` fields in Project are suggested to be removed because there's no benefit of knowing the creator and supervisors are participants.

I agree for `creator`, but not for `supervisor`. It's important to know who supervises a project. We can check participant who has supervisor role, though, but since supervisor can be called quite frequently, I think it's better to keep in a separate field.

**Comment by McSinyx** [comment]
Then shall we separate to two arrays, i.e. `supervisors` and `students` (there's no academic restriction for a project to have only one supervisor)?  For the project's page it's necessary to display the supervisor(s) and student(s) separately, I think.

**Comment by Huy-Ngo** [comment]
> there's no academic restriction for a project to have only one supervisor.

I agree. Even if our school has such rule, let's not assume other schools that may use this do not.

But as far as I'm aware, one supervisor is the general case, so enforcing arrays may be overhead.

**Comment by McSinyx** [comment]
I know a BI8 student with two mentors for his internship, so it's not even impossible in our university.

**Comment by Huy-Ngo** [comment]
> so enforcing arrays may be overhead

I'm not sure if enforcing arrays is overhead or having two data types is overhead :sweat_smile:
