### ISSUE TITLE
Landing page for user and non-user

### ISSUE THREAD

**Issue by Huy-Ngo** [Huy-Ngo/acanban#77]
Previously, the landing page/homepage for non-user is a brief introduction of our app, but it's removed in #73 and is replaced by some example paragraphs and forms, so I suggest reverting back.

However, it shouldn't be that for signed in user. I suppose it should be something useful for user, such as the current project page (if there is one project) or list of current projects (if there are several).

**Comment by McSinyx** [comment]
Relevant but not exactly identical: GH-64.

**Comment by Huy-Ngo** [comment]
Eh I forgot I already made that 😔

**Comment by McSinyx** [comment]
Closing in favor of GH-64.
