### ISSUE TITLE
Use Jinja comments for copyright header in templates

### ISSUE THREAD

**Issue by McSinyx** [Huy-Ngo/acanban#88]
Currently the generated HTMLs are polluted with inaccurate copyright headers (in the sense that generated data are not copyrighted).  Instead, we should use [Jinja comments](https://jinja.palletsprojects.com/en/2.11.x/templates/#comments) to specify the copyright only in the templates, e.g.

```jinja
{#
 # Base HTML template
 # Copyright (C) ...
 #
 # This file is part of Acanban.
 #
 # Acanban is free software: you can redistribute it and/or modify
 # it under the terms of the GNU Affero General Public License as published
 # by the Free Software Foundation, either version 3 of the License, or
 # (at your option) any later version.
 #
 # Acanban is distributed in the hope that it will be useful,
 # but WITHOUT ANY WARRANTY; without even the implied warranty of
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 # GNU Affero General Public License for more details.

 # You should have received a copy of the GNU Affero General Public License
 # along with Acanban.  If not, see <https://www.gnu.org/licenses/>.
 #}
```

**Comment by Huy-Ngo** [comment]
The HTML comments aren't OK?

**Comment by McSinyx** [comment]
See [this for instance](view-source:https://acanban.ga).  We only have the copyright over the templates, not the machine generated document.  It gets tricky when the page involve user's data, where the header implies we own them :smile:

**Comment by Huy-Ngo** [comment]
> have the copyright over the templates, not the machine generated document

OK got it.

**Comment by McSinyx** [comment]
Not-so-gentle boioioing!
