### ISSUE TITLE
Use label for label instead of placeholders

### ISSUE THREAD

**Issue by McSinyx** [Huy-Ngo/acanban#92]
As [noted on MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#Labels),

> The `placeholder` attribute lets you specify text that appears within the `<input>` element's content area itself when it is empty. The placeholder should never be required in order to understand your forms. It is not a label, and should not be used as a substitute, because it isn't. **The placeholder is used to provide a hint as to what an inputted value should look like, not an explanation or prompt.**
>
> Not only is the placeholder not accessible to screen readers, but once the user enters any text into the form control, or if the form control already has a value, the placeholder disappears. Browsers with automatic page translation features may skip over attributes when translating, meaning the placeholder may not get translated.

Since you're familiar with the authentication pages, do you want to fix my previous mistakes this to warm up, @DDHLong?

**Comment by DDHLong** [comment]
i wonder can the icon do the job as well as the label?

**Comment by McSinyx** [comment]
For consistency, I personally advice against it, since it would be difficult to find suitable ones for every field.  You can file an issue regarding it but let's not spend precious working hours on cosmetic improvements.
